<?php echo $this->doctype('XHTML1_TRANSITIONAL'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl() . '/css/site.css'); ?>
</head>
<body>
<div id="content">
	<h1><?php echo $this->escape($this->title); ?></h1>
	<?php echo $this->layout()->content; ?>
</div>
</body>
</html>
